[package]
name = "smart_road"
version = "0.1.0"
edition = "2024"
authors = ["Damien <damienprouet76@gmail.com>"]

[dependencies]
sdl2 = { version = "0.37", features = ["image"] }
rand = "0.9.2"

[profile.release]
opt-level = 3
lto = true
